services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Diez.cinco5
      MYSQL_DATABASE: rfelipe_db
      MYSQL_USER: rfelipe
      MYSQL_PASSWORD: cAAnKz
    ports:
      - "3306:3306"

  php:
    build: .
    restart: always
    volumes:
      - ./PHP:/var/www/html/PHP
      - ./HTML:/var/www/html/HTML
      - ./CSS:/var/www/html/CSS
    ports:
      - "8080:80"
    depends_on:
      - mysql
