version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: rfelipe_db
      MYSQL_USER: rfelipe
      MYSQL_PASSWORD: Diez.cinco5
    ports:
      - "3306:3306"

  php:
    build: .
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    
